language: node_js
node_js:
  - "10"

cache: npm

git:
  depth: 3

before_script:
  - npm run build:prod

script:
  - npm run lint
  - npm test -- --ci --color --verbose

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  verbose: true
  on:
    branch: master
