language: node_js
node_js:
  - "8"

git:
  depth: 3

before_script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: develop
